/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\hp\Desktop\portfolio_three\first-project\src\assets\models\click_pointer.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/click_pointer.glb')
  return (
    <a.group {...props} dispose={null}>
      <mesh geometry={nodes.pointer.geometry} material={nodes.pointer.material} position={[-7.348, 15.762, -48.286]} rotation={[0, 0.129, -Math.PI / 2]} scale={[-0.189, -0.188, -0.128]} />
      <a.group position={[-7.371, 11.168, -48.539]} rotation={[Math.PI / 2, -0.129, Math.PI / 2]} scale={0.092}>
        <mesh geometry={nodes.Plane019.geometry} material={materials.black} />
        <mesh geometry={nodes.Plane019_1.geometry} material={materials.blanco} />
      </a.group>
      <mesh geometry={nodes.pointer001.geometry} material={nodes.pointer001.material} position={[-3.038, 15.762, -48.286]} rotation={[0, 0.129, -Math.PI / 2]} scale={[-0.189, -0.188, -0.128]} />
      <mesh geometry={nodes.pointer002.geometry} material={nodes.pointer002.material} position={[1.281, 15.762, -48.286]} rotation={[0, 0.129, -Math.PI / 2]} scale={[-0.189, -0.188, -0.128]} />
      <a.group position={[-3.044, 11.168, -48.539]} rotation={[Math.PI / 2, -0.129, Math.PI / 2]} scale={0.092}>
        <mesh geometry={nodes.Plane024.geometry} material={materials.black} />
        <mesh geometry={nodes.Plane024_1.geometry} material={materials.blanco} />
      </a.group>
      <a.group position={[1.161, 11.168, -48.539]} rotation={[Math.PI / 2, -0.129, Math.PI / 2]} scale={0.092}>
        <mesh geometry={nodes.Plane025.geometry} material={materials.black} />
        <mesh geometry={nodes.Plane025_1.geometry} material={materials.blanco} />
      </a.group>
    </a.group>
  )
}

useGLTF.preload('/click_pointer.glb')
