/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\hp\Desktop\portfolio_three\first-project\src\assets\models\sculpture_peco.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sculpture_peco.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Peco_Peco.geometry} material={materials.bronze_2} position={[35.143, 8.576, -14.598]} rotation={[0, -0.163, 0]} scale={0.156} />
    </group>
  )
}

useGLTF.preload('/sculpture_peco.glb')
