/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\hp\Desktop\NPP\first-project\src\assets\textures\book_anim.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/book_anim.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="portada" position={[0, 0.05, 0]}>
          <group name="Empty_circle" rotation={[Math.PI / 2, 0, 0]} scale={0.25} />
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.fornt} position={[0.8, 0, 0]} scale={[0.8, 1, 1]} />
        </group>
        <group name="shee1" position={[0, 0.05, 0]}>
          <group name="Empty_circle002" rotation={[Math.PI / 2, 0, 0]} scale={0.25} />
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[0.8, 0, 0]} scale={[0.795, 0.994, 0.994]} />
        </group>
        <group name="sheet2" position={[0, 0.05, 0]}>
          <group name="Empty_circle001" position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.25} />
          <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[0.8, 0.001, 0]} scale={[0.795, 0.994, 0.994]} />
        </group>
        <group name="sheet3" position={[0, 0.05, 0]}>
          <group name="Empty_circle003" position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.25} />
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[0.8, 0.001, 0]} scale={[0.795, 0.994, 0.994]} />
        </group>
        <group name="sheet4" position={[0, 0.05, 0]}>
          <group name="Empty_circle004" position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.25} />
          <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} position={[0.8, 0.001, 0]} scale={[0.795, 0.994, 0.994]} />
        </group>
        <group name="sheet5" position={[0, 0.05, 0]}>
          <group name="Empty_circle005" position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.25} />
          <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[0.8, 0.001, 0]} scale={[0.795, 0.994, 0.994]} />
        </group>
        <group name="sheet6" position={[0, 0.05, 0]}>
          <group name="Empty_circle006" position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.25} />
          <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} position={[0.8, 0.001, 0]} scale={[0.795, 0.994, 0.994]} />
        </group>
        <mesh name="cubierta" geometry={nodes.cubierta.geometry} material={materials.fornt} position={[0.8, -0.037, 0]} scale={[0.8, 1, 1]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.spine} position={[0.001, 0.018, 0]} scale={[0.006, 0.025, 0.996]} />
        <mesh name="papers" geometry={nodes.papers.geometry} material={nodes.papers.material} position={[0.8, 0, 0]} scale={[0.8, 1, 1]} />
      </group>
    </group>
  )
}

useGLTF.preload('/book_anim.glb')
