/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 C:\Users\hp\Desktop\portfolio_three\first-project\src\assets\models\hand.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hand.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['15797_Pointer_v1_new'].geometry} material={materials._15797_Pointer_v1_15797_Pointer_v1default} position={[1.746, 1.092, -0.505]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
    </group>
  )
}

useGLTF.preload('/hand.glb')
